# /etc/claw/claw.conf
# Main Claw configuration file

# Default boot target
default_target: claw-multiuser.target

# Default cwd for service start/stop/reload commands.
# Individual service files can override this with working_dir.
default_working_dir: /

# Log settings
log_level: info
log_dir: /var/log/claw
